### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by breezykermo** [clairecut/clairecut-app#1]
What do you guys think about some code review for all the hacky code we've written? It would allow us to roadmap and remind ourselves, and identify issues.

**Comment by andrekovac** [comment]
Hi, I made some major updates to the code and got it running with the back-end! Give it a try! I fully tested it with a real iOS device. Your photo will show up in the Boards Tab and the server should send back cut out pieces and display them in the Pieces Tab. I got it running on Android, but the simulator somehow didn't send the server request.. have to test it on a real Android device.

**Comment by andrekovac** [comment]
I closed this issue because the code is no refactored in an ok shape to continue to work with it. I wrote done the next stuff we should do into TODO.md in this repo. Feel free to add stuff there.

**Comment by breezykermo** [comment]
Sweet, thanks André.![](https://link.nylas.com/open/exx4j1thzy9qahmxabdctutv1
/local-
10824ea0-2884?r=cmVwbHkrMDBmYmI0ZjBkYmUxNDkyN2U5NDRiMzMyYzU4YjhjODY5ZjU0ODExN2E2NzQ5Mzc4OTJjZjAwMDAwMDAxMTM4ZmJlZjU5MmExNjljZTA5OWRlYjc0QHJlcGx5LmdpdGh1Yi5jb20=)
